package:
  name: fix-bridge-client
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - abseil-cpp
    - catch2
    - nlohmann_json
    - roq-client
    - roq-eb
    - roq-fix-bridge
    - roq-io
    - roq-oss-tomlplusplus

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FIX Bridge client (a template project)
