package:
  name: roq-fix-proxy
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ ROQ_BUILD_NUMBER if ROQ_BUILD_NUMBER is defined else GIT_DESCRIBE_NUMBER }}
  script_env:                                                                                                           
    - ROQ_BUILD_NUMBER                                                                                                  
    - ROQ_BUILD_TYPE                                                                                                    
  run_exports:                                                                                                          
    - {{ pin_subpackage('roq-fix-proxy', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
  host:
    - abseil-cpp
    - benchmark
    - catch2  # [linux]
    - nlohmann_json
    - roq-client
    - roq-fix-codec
    - roq-flags
    - roq-io
    - roq-oss-catch2  # [osx]
    - roq-oss-libevent
    - roq-oss-tomlplusplus
    - roq-utils
    - roq-web

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq FIX Proxy
